### ISSUE TITLE
Reorganize modules

### ISSUE THREAD

**Issue by vloncar** [vlimant/NNLO#9]
Currently, the project places all its logic under `mpi_learn` module, which makes little sense now that optimization is also included. I propose that we either remove one level or rename `mpi_learn` to `nnlo` and reorganize within. The reorganized structure would contain:

```
train
    algo.py
    data.py
    model.py
    optimizer.py
mpi
    manager.py
    process.py
    single.py (potentially fused into process.py)
optimize
    coordinator.py
    process_block.py (possibly renamed to block.py)
util
    logger.py
    misc.py (renamed from current utils.py)
    monitor.py
    timeline.py
```

I can do this as part of #8 or as a separate PR after that one is merged.

**Comment by vlimant** [comment]
#8 is merged. 
the structure looks fine to me
